[project]
name = "UWGS-Onboarding-Challenge"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]==0.115.0",
    "loguru==0.7.2",
    "sqlmodel==0.0.22",
]

[build-system]
requires = ["setuptools>=59.0", "wheel"]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-vvv"
testpaths = ["test/backend"]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pytest==8.3.3",
]

[tool.ruff]
line-length = 88
include = [
    # "backend/**/*.py",
    "backend/api/endpoints/command.py",
    "backend/api/middlewares/logger_middleware.py",
    "backend/data/data_models.py",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "UP",
    # # https://github.com/UWOrbital/GS-Onboarding/blob/main/README.md
    "ANN",
    "N",
    # "D",
]
ignore = ["E501"]
