[build-system]
requires = ["setuptools>=59.0", "wheel"]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=gs --cov=obc/tools/python -v"
testpaths = ["test/backend"]
